name : Laravel CI

on: [push]

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: laravel
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, pdo, pdo_mysql, mbstring, tokenizer, xml, curl, json, gd, zip

      - name: Install packages
        run: |
          composer install --no-interaction


